### ISSUE TITLE
Function Specification

### ISSUE THREAD

**Issue by wang-rui** [UBC-MDS/Rgram#1]
Complete the function specification for Rgram functions:

- [x] 1. Flipping @mgaroub 
- [x] 2. Padding @wang-rui 
- [x] 3. Rotating @jiajie0225 
- [x] 4. Grayscale @AishwaryaGopal12 

For this milestone you will write R function documentation that will serve as specifications, but you will NOT write any code for your package functions. Specifically, set-up empty functions (with appropriate function names) containing no code in the files where you will eventually write code. Write function documentation (e.g., complete roxygen2 comments). These are the functions you wrote about in your proposal.

**Comment by mgaroub** [comment]
Updated the description of the issue
