### ISSUE TITLE
Create R repo and project structure

### ISSUE THREAD

**Issue by wang-rui** [UBC-MDS/Rgram#5]
- [x] The name of the repository should be relevant to the package/project topics.

- [x] For now choose the MIT license. You may change it later when you learn more about licenses.

- [x] Use usethis::use_code_of_conduct to add a code of conduct. You may want to customize it further to suit your group.

- [x] Add the team members as authors to the DESCRIPTION file.

- [x] Use usethis::use_tidy_contributing() to add a CONTRIBUTING.md file to your package. This file will live in .github and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.

Outline the package you would like to build in the README.Rmd file. (This can be identical for both projects at this point in the project). In particular, your README.md should contain:

- [x] a summary paragraph that describes the project at a high level

- [x] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [x] a paragraph describing where your packages fit into the R ecosystem (are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).

**Comment by mgaroub** [comment]
Ignore this. I updated the description of the issue.

- [x] The name of the repository should be relevant to the package/project topics.

- [x] For now choose the MIT license. You may change it later when you learn more about licenses.

- [ ] Use usethis::use_code_of_conduct to add a code of conduct. You may want to customize it further to suit your group.

- [ ] Add the team members as authors to the DESCRIPTION file.

- [ ] Use usethis::use_tidy_contributing() to add a CONTRIBUTING.md file to your package. This file will live in .github and it will create that folder if it does not already exist. Edit the boiler plate document this gives to to reflect your contribution strategy that your team has agreed upon.

Outline the package you would like to build in the README.Rmd file. (This can be identical for both projects at this point in the project). In particular, your README.md should contain:

- [ ] a summary paragraph that describes the project at a high level

- [ ] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [ ] a paragraph describing where your packages fit into the R ecosystem (are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
